"""Initial

Revision ID: 0e531dcb2470
Revises: 005ce6e94401
Create Date: 2023-09-21 16:20:31.475496

"""


# revision identifiers, used by Alembic.
revision = '0e531dcb2470'
down_revision = '005ce6e94401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
