"""unit

Revision ID: 76f64d712ebe
Revises: d10c0db322ab
Create Date: 2023-09-21 17:32:17.770021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76f64d712ebe'
down_revision = 'd10c0db322ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'] ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'] ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'] ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('messages')
    op.drop_table('friends')
    # ### end Alembic commands ###
