"""unit

Revision ID: c310a12122ae
Revises: 0e531dcb2470
Create Date: 2023-09-21 17:15:38.027161

"""


# revision identifiers, used by Alembic.
revision = 'c310a12122ae'
down_revision = '0e531dcb2470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
