"""unit

Revision ID: d10c0db322ab
Revises: c310a12122ae
Create Date: 2023-09-21 17:31:07.951303

"""


# revision identifiers, used by Alembic.
revision = 'd10c0db322ab'
down_revision = 'c310a12122ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
